// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Samurai1;

namespace Samurai1.Migrations
{
    [DbContext(typeof(SamuraiContext))]
    [Migration("20180911074458_AddedClasses2")]
    partial class AddedClasses2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Samurai1.HairStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SamuraiIdId");

                    b.HasKey("Id");

                    b.HasIndex("SamuraiIdId");

                    b.ToTable("HairStyles");
                });

            modelBuilder.Entity("Samurai1.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SamuraiIdId");

                    b.HasKey("Id");

                    b.HasIndex("SamuraiIdId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("Samurai1.Samurai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Samurais");
                });

            modelBuilder.Entity("Samurai1.HairStyle", b =>
                {
                    b.HasOne("Samurai1.Samurai", "SamuraiId")
                        .WithMany()
                        .HasForeignKey("SamuraiIdId");
                });

            modelBuilder.Entity("Samurai1.Quote", b =>
                {
                    b.HasOne("Samurai1.Samurai", "SamuraiId")
                        .WithMany()
                        .HasForeignKey("SamuraiIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
