// <auto-generated />
using System;
using CheckPoint06;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CheckPoint06.Migrations
{
    [DbContext(typeof(SpaceshipContext))]
    [Migration("20180914071409_RavioliAdded")]
    partial class RavioliAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CheckPoint06.Ravioli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BestBefore");

                    b.Property<DateTime>("Packed");

                    b.HasKey("Id");

                    b.ToTable("Ravioli");
                });

            modelBuilder.Entity("CheckPoint06.RavioliInSpaceship", b =>
                {
                    b.Property<int>("RavioliId");

                    b.Property<int>("SpaceshipId");

                    b.HasKey("RavioliId", "SpaceshipId");

                    b.HasIndex("SpaceshipId");

                    b.ToTable("RavioliInSpaceship");
                });

            modelBuilder.Entity("CheckPoint06.Spaceship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("CheckPoint06.RavioliInSpaceship", b =>
                {
                    b.HasOne("CheckPoint06.Ravioli", "Ravioli")
                        .WithMany()
                        .HasForeignKey("RavioliId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CheckPoint06.Spaceship", "Spaceship")
                        .WithMany()
                        .HasForeignKey("SpaceshipId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
